#!/bin/bash
#$ -S /bin/bash

#Written by Stav Yagev, 2013

matlab2013a -nodisplay -r "addpath(genpath('~/WeizGrid')); load('~/.matlab/cluster_jobs/$1/$2_$3i'); workFunc=@$4; WGdowork; save('~/.matlab/cluster_jobs/$1/$2_$3o','WGres','mAssRng','bSuccess'); quit;"